- id: homeassistant_on
  alias: Alerta de detención
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: notify.mypushbullet
    data_template:
      title: "Control de hidroponia ONLINE"
      message: "Se ha iniciado el control de hidroponia"

- id: homeassistant_off
  alias: Alerta de inicio
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    service: notify.mypushbullet
    data_template:
      title: "Control de hidroponia OFFLINE"
      message: "Se ha detenido el control de hidroponia"

###################
#HUMEDAD
###################
#INFERIOR AL 60%
- id: humedad_inf
  alias: Humedad > 60%
  trigger:
    - platform: numeric_state
      entity_id: sensor.humedad
      below: 60
  condition:
    condition: state
    entity_id: switch.humidificador_ambiente
    state: 'off'
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La humedad ambiente descendió del 60%"
        message: "La humedad ambiente es de: {{ states.sensor.humedad_ambiente.state }}%, accionando humidificador"
    - service: mqtt.publish
      data:
        topic: "invernadero/humidificador/switch/set"
        payload: "on"
#SUPERIOR AL 80%
- id: humedad_sup
  alias: Humedad < 80%
  trigger:
    - platform: numeric_state
      entity_id: sensor.humedad
      above: 80
  condition:
    condition: state
    entity_id: switch.humidificador_ambiente
    state: 'on'
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La humedad ambiente superó el 80%"
        message: "La humedad ambiente es de: {{ states.sensor.humedad_ambiente.state }}%, deteniendo humidificador"
    - service: mqtt.publish
      data:
        topic: "invernadero/humidificador/switch/set"
        payload: "off"

- id: travis_automation
  alias: 'Update if Travis=passed'
  trigger:
    platform: state
    entity_id: sensor.sorianojuanhomeassistant_last_build_state
    to: 'passed'
  action:
    - service: script.update_config


#- id: nodemcu_online
#  alias: NodeMCU online
#  trigger:
#    platform: mqtt
#    topic: status/nodemcu
#    payload: online
#  action:
#    service: notify.mypushbullet
#    data_template:
#      title: "NodeMCU online"
#      message: "Se conecto el NodeMCU"