#######################
#ALERTAS
#######################

- id: homeassistant_on
  alias: Alerta de detención
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: notify.mypushbullet
    data_template:
      title: "Control de hidroponia ONLINE"
      message: "Se ha iniciado el control de hidroponia"

- id: homeassistant_off
  alias: Alerta de inicio
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    service: notify.mypushbullet
    data_template:
      title: "Control de hidroponia OFFLINE"
      message: "Se ha detenido el control de hidroponia"

- id: sensor_offline
  alias: Sensor offline
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.temp_online_timeout
        - binary_sensor.hum_online_timeout
      to: "off"
  action:
    - service: notify.mypushbullet
      data_template:
        title: "Un nodo se ha desconectado"
        message: "No se han recibido actualizaciones de un nodo por más del tiempo establecido"


###################
#HUMEDAD
###################
#INFERIOR AL MIN
- id: humedad_inf
  alias: Humedad < Min
  trigger:
    - platform: state
      entity_id: binary_sensor.hum_threshold_min
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.humidificador_ambiente
        state: 'off'
      - condition: state
        entity_id: input_boolean.control_humedad
        state: "on"
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La humedad ambiente descendió del mínimo establecido: {{ states.input_number.humedad_min.state }}%"
        message: "La humedad ambiente es de: {{ states.sensor.humedad_ambiente.state }}%, accionando humidificador"
    - service: mqtt.publish
      data:
        topic: "invernadero/humidificador/switch/set"
        payload: "on"
        qos: 1
#SUPERIOR AL MAX
- id: humedad_sup
  alias: Humedad > Max
  trigger:
    - platform: state
      entity_id: binary_sensor.hum_threshold_max
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.humidificador_ambiente
        state: 'on'
      - condition: state
        entity_id: input_boolean.control_humedad
        state: "on"
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La humedad ambiente superó el máximo establecido: {{ states.input_number.humedad_max.state }}%"
        message: "La humedad ambiente es de: {{ states.sensor.humedad_ambiente.state }}%, deteniendo humidificador"
    - service: mqtt.publish
      data:
        topic: "invernadero/humidificador/switch/set"
        payload: "off"
        qos: 1

#############
#TEMPERATURA
#############
#INFERIOR AL MIN
- id: temperatura_inf
  alias: Temperatura < Min
  trigger:
    #Se descendió del mínimo ingresado
    - platform: state
      entity_id: binary_sensor.temp_threshold_min
      to: 'on'
  condition:
    condition: and
    conditions:
      #Están apagadas las estufas
      - condition: state
        entity_id: switch.switch.estufa_1
        state: 'off'
      #Está activado el control automático de temperatura
      - condition: state
        entity_id: input_boolean.control_temperatura
        state: "on"
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La temperatura ambiente descendió del mínimo establecido: {{ states.input_number.temp_min.state }}%"
        message: "La temperatura ambiente es de: {{ states.sensor.temperatura_ambiente.state }}°C, prendiendo estufas"
    - service: mqtt.publish
      data:
        topic: "invernadero/estufa1/switch/set"
        payload: "on"
        qos: 1
#SUPERIOR AL MAX
- id: temperatura_sup
  alias: Temperatura > Max
  trigger:
    #Se superó el máximo ingresado
    - platform: state
      entity_id: binary_sensor.temp_threshold_max
      to: 'on'
  condition:
    condition: and
    conditions:
      #Están cerradas las ventanas
      - condition: state
        entity_id: switch.switch.ventana_1
        state: 'off'
      - condition: state
        entity_id: switch.switch.ventana_2
        state: 'off'
      - condition: state
        entity_id: switch.switch.ventana_3
        state: 'off'
      - condition: state
        entity_id: switch.switch.ventana_4
        state: 'off'
      #Está activado el control automático de temperatura
      - condition: state
        entity_id: input_boolean.control_temperatura
        state: "on"
  action:
    - service: notify.mypushbullet
      data_template:
        title: "La temperatura ambiente superó el máximo establecido: {{ states.input_number.temp_max.state }}%"
        message: "La temperatura ambiente es de: {{ states.sensor.temperatura_ambiente.state }}°C, abriendo ventanas"
      #Abrir ventanas_gral
    - service: mqtt.publish
      data:
        topic: "invernadero/ventanas_gral/switch/set"
        payload: "on"
        qos: 1
      #Abrir ventana 1 por 1
    - service: mqtt.publish
      data:
        topic: "invernadero/ventana1/switch/set"
        payload: "on"
        qos: 1
    - service: mqtt.publish
      data:
        topic: "invernadero/ventana2/switch/set"
        payload: "on"
        qos: 1
    - service: mqtt.publish
      data:
        topic: "invernadero/ventana3/switch/set"
        payload: "on"
        qos: 1
    - service: mqtt.publish
      data:
        topic: "invernadero/ventana4/switch/set"
        payload: "on"
        qos: 1











##############
# ETC
##############

- id: travis_automation
  alias: 'Update if Travis=passed'
  trigger:
    platform: state
    entity_id: sensor.sorianojuanhomeassistant_last_build_state
    to: 'passed'
  action:
    - service: script.update_config


############################
##################
#SHOW/HIDE
##################
############################

############
#INVERNADERO
############
#Hide
- id: hide_invernadero_graphs
  alias: Hide Invernadero Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_invernadero
      to: "off"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_invernadero
    data:
      visible: False
#Show
- id: show_invernadero_graphs
  alias: Show Invernadero Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_invernadero
      to: "on"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_invernadero
    data:
      visible: True
############
#PLANTAS
############
#Planta1
#Hide
- id: hide_planta1_graphs
  alias: Hide Planta1 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta1
      to: "off"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta1
    data:
      visible: False
#Show
- id: show_planta1_graphs
  alias: Show Planta1 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta1
      to: "on"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta1
    data:
      visible: True
#-----------
#Planta2
#Hide
- id: hide_planta2_graphs
  alias: Hide Planta2 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta2
      to: "off"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta2
    data:
      visible: False
#Show
- id: show_planta2_graphs
  alias: Show Planta2 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta2
      to: "on"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta2
    data:
      visible: True
#------------
#Planta3
#Hide
- id: hide_planta3_graphs
  alias: Hide Planta3 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta3
      to: "off"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta3
    data:
      visible: False
#Show
- id: show_planta3_graphs
  alias: Show Planta3 Graphs
  trigger:
    - platform: state
      entity_id: input_boolean.show_hide_graphs_planta3
      to: "on"
  action:
    service: group.set_visibility
    entity_id: 
      - group.graficos_planta3
    data:
      visible: True