- platform: template
  sensors: 
    hum_threshold_min:
      entity_id:
        - input_number.humedad_min
        - sensor.humedad_ambiente
      value_template: >-
        {{ states('sensor.humedad_ambiente')|float < states('input_number.humedad_min')|float }}
    hum_threshold_max:
      entity_id:
        - input_number.humedad_min
        - sensor.humedad_ambiente
      value_template: >-
        {{ states('sensor.humedad_ambiente')|float < states('input_number.humedad_min')|float }}