#- platform: mqtt
#  devices:
#    NodeMCU: 'status/nodemcu'
#    Prueba:  'status/prueba'
#
- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
  waypoint_whitelist:
    - TorcePhone
- platform: ping
  home_interval: 1
  hosts:
    NodeMCU: 192.168.4.4
    ESPRepeater: 192.168.4.1
    Dell: 192.168.4.5