#sensor: Forecast
- platform: yr
  name: Pronostico
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature
#sensor 2: 
- platform: time_date
  display_options:
    - "date_time"
#sensor 3:
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: ipv4_address
      arg: wlan0
#sensor 4: Speedtest
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
#sensor 5: Temperatura
- platform: mqtt
  name: "Temperatura ambiente"
  state_topic: "sensor/temperature"
  qos: 0
  unit_of_measurement: "°C"
#sensor 6: Humedad
- platform: mqtt
  name: "Humedad ambiente"
  state_topic: "sensor/humidity"
  qos: 0
  unit_of_measurement: "%"
#sensor 7: Travis
- platform: travisci
  api_key: !secret travis_token
  scan_interval: 30
  default_branch: hidroponia
  repository_names:
    - home-assistant

#############
# PLANTA 1
#############
#sensor 8: Temperatura
- platform: mqtt
  name: "pH - planta 1"
  state_topic: "planta1/sensor/ph"
  qos: 0
  unit_of_measurement: "pH"
#sensor 9: Humedad
- platform: mqtt
  name: "Conductividad eléctrica - planta 2"
  state_topic: "planta1/sensor/ec"
  qos: 0
  unit_of_measurement: "Siemens"
#############
# PLANTA 2
#############
#sensor 5: Temperatura
- platform: mqtt
  name: "pH - planta 2"
  state_topic: "planta2/sensor/ph"
  qos: 0
  unit_of_measurement: "pH"
#sensor 6: Humedad
- platform: mqtt
  name: "Conductividad eléctrica - planta 2"
  state_topic: "planta2/sensor/ec"
  qos: 0
  unit_of_measurement: "Siemens"
#############
# PLANTA 3
#############
  #sensor 5: Temperatura
- platform: mqtt
  name: "pH - planta 3"
  state_topic: "planta3/sensor/ph"
  qos: 0
  unit_of_measurement: "pH"
#sensor 6: Humedad
- platform: mqtt
  name: "Conductividad eléctrica - planta 3"
  state_topic: "planta3/sensor/ec"
  qos: 0
  unit_of_measurement: "Siemens"